---
apiVersion: v1
kind: Namespace
metadata:
  name: freeipa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    openstack-app: freeipa
  name: freeipa
  namespace: freeipa
spec:
  clusterIP: None
  sessionAffinity: ClientIP
  ports:
  - port: 443
    protocol: TCP
---
apiVersion: "v1"
kind: "Endpoints"
metadata:
  labels:
    openstack-app: freeipa
  name: freeipa
  namespace: freeipa
subsets:
 - addresses:
      - ip: "10.20.0.10"
   ports:
      - port: 443
        protocol: TCP
        name: https