---
kind: "Template"
apiVersion: "v1"
metadata:
  name: efs-provisioner
objects:
  - kind: Deployment
    apiVersion: extensions/v1beta1
    metadata:
      name: efs-provisioner
    spec:
      replicas: 1
      strategy:
        type: Recreate 
      template:
        metadata:
          labels:
            app: efs-provisioner
        spec:
          containers:
            - name: efs-provisioner
              image: quay.io/external_storage/efs-provisioner:latest
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: AWS_ACCESS_KEY_ID
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: secrets
                      key: AWS_SECRET_ACCESS_KEY                
                - name: FILE_SYSTEM_ID
                  value: $(FILE_SYSTEM_ID)
                - name: AWS_REGION
                  valueFrom:
                    configMapKeyRef:
                      name: clusterconfiguration
                      key: aws.region
                - name: PROVISIONER_NAME
                  value: "aws-efs/aws-efs"
              volumeMounts:
                - name: pv-volume
                  mountPath: /persistentvolumes
          volumes:
            - name: pv-volume
              nfs:
                server: "$(FILE_SYSTEM_ID).efs.$(REGION).amazonaws.com"
                path: /
parameters:
  - name: "FILE_SYSTEM_ID"
    description: "File system id"
    required: true
    parameterType: "string"
  - name: "REGION"
    description: "region"
    required: true
    parameterType: "string"