---
kind: "Template"
apiVersion: "v1"
metadata:
  name: secrets
objects:
  - kind: "Secret"
    apiVersion: "v1"
    metadata:
      name: secrets
    data:
      AWS_SECRET_ACCESS_KEY: "$(AWS_SECRET_ACCESS_KEY)"
      AWS_ACCESS_KEY_ID: "$(AWS_ACCESS_KEY_ID)"
    type: "Opaque"
parameters:
  - name: "AWS_SECRET_ACCESS_KEY"
    description: "Amazon Secret Key"
    required: true
    parameterType: "string"
  - name: "AWS_ACCESS_KEY_ID"
    description: "Amazon Access Key"
    required: true
    parameterType: "string"
